CaiThuocLa/CaiThuocLa/CaiThuocLa/Controllers/SurveyQuestionController.cs
using CaiThuocLa.DAO;
using CaiThuocLa.DTO;
using CaiThuocLa.Models;
using CaiThuocLa.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaiThuocLa.Controllers
{
    public class SurveyQuestionController : BaseController
    {
        public SqlSurveyQuestionDao _surveyQuestion = new SqlSurveyQuestionDao();
        public SqlSurveyDao _survey = new SqlSurveyDao();

        //
        // GET: /Survey/

        public ActionResult Index(SurveyQuestionModel model)
        {
            if (model.CurrentPage != 0)
                model.Paging.CurrentPage = model.CurrentPage;
            else
                model.Paging.CurrentPage = 1;

            model.DataList = _surveyQuestion.GetWithFilter(
                                (int)model.Paging.PageSize,
                                (int)model.Paging.CurrentPage,
                                model.Question,
                                model.AnswersSearch,
                                model.SurveyID,
                                (short)model.Status
                                );
            if (model.DataList != null && model.DataList.Count() > 0)
            {
                var firstOrDefault = model.DataList.FirstOrDefault();
                if (firstOrDefault != null)
                    model.Paging.TotalRecords = (model.DataList.Any())
                        ? Convert.ToInt64(firstOrDefault.ExtentionProperty["TotalRec"].ToString())
                        : 0;
                else
                    model.Paging.TotalRecords = 0;

            }

            List<Survey> surveyList = new List<Survey>(_survey.GetAll());
            Survey surveyAll = new Survey();
            surveyAll.ID = -1;
            surveyAll.SurveyName = "Tất cả";
            surveyList.Add(surveyAll);
            ViewBag.SurveyList = new SelectList(surveyList, "ID", "SurveyName");

            ViewBag.SuccessMessage = (SuccessMessage != null) ? SuccessMessage : "";
            ViewBag.ErrorMessage = (ErrorMessage != null) ? ErrorMessage : "";
            SuccessMessage = "";
            ErrorMessage = "";
            return View(model);
        }

        public ActionResult _SurveyQuestionPatial(Int64 pid)
        {
            var list = new List<SurveyQuestion>(_surveyQuestion.GetBySurveyID(pid));
            return View(list);
        }

        [HttpGet]
        public ActionResult Add()
        {
            SurveyQuestionModel model = new SurveyQuestionModel();
            List<Survey> surveyList = new List<Survey>(_survey.GetAll());
            ViewBag.SurveyList = new SelectList(surveyList, "ID", "SurveyName");
            return View(model);
        }

        [HttpGet]
        public ActionResult AddPatial(Int64 pid)
        {
            SurveyQuestionModel model = new SurveyQuestionModel();
            model.SurveyID = pid;
            model.returnUrl = "/Survey";
            List<Survey> surveyList = new List<Survey>(_survey.GetAll());
            ViewBag.SurveyList = new SelectList(surveyList, "ID", "SurveyName");
            return View("Add", model);
        }

        [HttpPost]
        public ActionResult Add(SurveyQuestionModel model)
        {
            SurveyQuestion item = new SurveyQuestion();
            item.AssignProperties(model);
            item.CreatedDate = DateTime.Now;
            item.UpdatedDate = item.CreatedDate;

            if (_surveyQuestion.Insert(item))
            {
                SuccessMessage = "Đã nhập thông tin khảo sát thành công";
            }
            else
            {
                ErrorMessage = "Cập nhật thất bại";
            }
            if (String.IsNullOrEmpty(model.returnUrl))
                return Redirect("/SurveyQuestion");
            return Redirect(model.returnUrl);
        }

        [HttpGet]
        public ActionResult Edit(Int64 id)
        {
            SurveyQuestion item = _surveyQuestion.GetByID(id);
            SurveyQuestionModel model = new SurveyQuestionModel();
            model.AssignProperties(item);
            List<Survey> surveyList = new List<Survey>(_survey.GetAll());
            ViewBag.SurveyList = new SelectList(surveyList, "ID", "SurveyName");
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(SurveyQuestionModel model)
        {
            SurveyQuestion item = new SurveyQuestion();
            item.AssignProperties(model);
            item.UpdatedDate = DateTime.Now;

            if (_surveyQuestion.Update(item))
            {
                SuccessMessage = "Đã cập nhật thành công";
            }
            else
            {
                ErrorMessage = "Cập nhật thất bại";
            }

            if (String.IsNullOrEmpty(model.returnUrl))
                return Redirect("/SurveyQuestion");
            return Redirect(model.returnUrl);
        }

        [HttpGet]
        public ActionResult EditPatial(Int64 id)
        {
            SurveyQuestion item = _surveyQuestion.GetByID(id);
            SurveyQuestionModel model = new SurveyQuestionModel();
            model.returnUrl = "/Survey";
            model.AssignProperties(item);
            List<Survey> surveyList = new List<Survey>(_survey.GetAll());
            ViewBag.SurveyList = new SelectList(surveyList, "ID", "SurveyName");
            return View("Edit", model);
        }

        public ActionResult Delete(Int64 id)
        {
            SurveyQuestion item = _surveyQuestion.GetByID(id);
            item.Status = SurveyQuestionStatus.Đã_xóa;

            if (_surveyQuestion.Update(item))
            {
                Survey survey = _survey.GetByID(item.SurveyID);
                survey.TotalQuestion--;
                _survey.Update(survey);

                SuccessMessage = "Đã xóa thành công";
            }
            else
            {
                ErrorMessage = "Xóa thất bại";
            }
            return Redirect("/SurveyQuestion");
        }

        public ActionResult DeletePatial(Int64 id)
        {
            SurveyQuestion item = _surveyQuestion.GetByID(id);
            item.Status = SurveyQuestionStatus.Đã_xóa;
            if (_surveyQuestion.Update(item))
            {
                SuccessMessage = "Đã xóa thành công";
            }
            else
            {
                ErrorMessage = "Xóa thất bại";
            }
            return Redirect("/Survey");
        }
    }
}

CaiThuocLa/CaiThuocLa/CaiThuocLa/Views/SurveyQuestion/Add.cshtml
@using CaiThuocLa.Code
@using CaiThuocLa.Utility
@model CaiThuocLa.Models.SurveyQuestionModel

@{
    Layout = "";
}

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <form id="form4" role="form" action="@Url.Action("Add", "SurveyQuestion", new { url = Request.QueryString["url"] })" method="post">
                        <div class="form-group">
                            <label class="control-label">Câu hỏi</label>
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.Question, new { @class = "form-control", style = "width:500px;" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Câu trả lời 1</label>
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.Answers1, new { @class = "form-control", style = "width:500px;" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Câu trả lời 2</label>
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.Answers2, new { @class = "form-control", style = "width:500px;" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Câu trả lời 3</label>
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.Answers3, new { @class = "form-control", style = "width:500px;" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Câu trả lời 4</label>
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.Answers4, new { @class = "form-control", style = "width:500px;" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Trạng thái</label>
                            <div class="input-icon right">
                                <i class="fa"></i>
                                @Html.EnumDropDownListFor(model => model.Status, null, "", new { @class = "form-control" }, new string[] { SurveyQuestionStatus.Đã_xóa.ToString() })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Thứ tự gửi</label>
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.QuestionContinueID, new { @class = "form-control", style = "width:500px;" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Khảo sát</label>
                            <div class="input-icon right">
                                <i class="fa"></i>
                                @if(!String.IsNullOrEmpty(Model.returnUrl))
                                { 
                                    @Html.DropDownList("SurveyID", (SelectList)ViewBag.SurveyList, new { @class = "form-control" ,  @disabled = "disabled" })
                                }
                                else
                                {
                                    @Html.DropDownList("SurveyID", (SelectList)ViewBag.SurveyList, new { @class = "form-control" })
                                }
                            </div>
                        </div>
                        @Html.HiddenFor(model => model.ID)
                        @Html.HiddenFor(model => model.returnUrl)
                        @Html.HiddenFor(model => model.SurveyID)
                        <div class="form-group text-center">
                            <button class="btn btn-danger" onclick="javascript:$('#form4').parsley('validate');">Thêm</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

CaiThuocLa/CaiThuocLa/CaiThuocLa/Views/SurveyQuestion/Edit.cshtml
@using CaiThuocLa.Code
@using CaiThuocLa.Utility
@model CaiThuocLa.Models.SurveyQuestionModel

@{
    Layout = "";
}

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <form id="form4" role="form" action="@Url.Action("Edit", "SurveyQuestion", new { url=Request.QueryString["url"] })" method="post">
                        <div class="form-group">
                            <label class="control-label">Câu hỏi</label>
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.Question, new { @class = "form-control", style = "width:500px;" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Câu trả lời 1</label>
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.Answers1, new { @class = "form-control", style = "width:500px;" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Câu trả lời 2</label>
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.Answers2, new { @class = "form-control", style = "width:500px;" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Câu trả lời 3</label>
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.Answers3, new { @class = "form-control", style = "width:500px;" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Câu trả lời 4</label>
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.Answers4, new { @class = "form-control", style = "width:500px;" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Trạng thái</label>
                            <div class="input-icon right">
                                <i class="fa"></i>
                                @Html.EnumDropDownListFor(model => model.Status, null, "", new { @class = "form-control" }, new string[] { SurveyQuestionStatus.Đã_xóa.ToString() })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Thứ tự gửi</label>
                            <div class="input-icon right">
                                @Html.TextBoxFor(model => model.QuestionContinueID, new { @class = "form-control", style = "width:500px;" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Khảo sát</label>
                            <div class="input-icon right">
                                <i class="fa"></i>
                                @if (!String.IsNullOrEmpty(Model.returnUrl))
                                {
                                    @Html.DropDownList("SurveyID", (SelectList)ViewBag.SurveyList, new { @class = "form-control", @disabled = "disabled" })
                                }
                                else
                                {
                                    @Html.DropDownList("SurveyID", (SelectList)ViewBag.SurveyList, new { @class = "form-control" })
                                }
                            </div>
                        </div>
                        @Html.HiddenFor(model => model.CreatedDate)
                        @Html.HiddenFor(model => model.ID)
                        @Html.HiddenFor(model => model.returnUrl)
                        @Html.HiddenFor(model => model.SurveyID)
                        <div class="form-group text-center">
                            <button class="btn btn-danger" onclick="javascript:$('#form4').parsley('validate');">Cập nhật</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

CaiThuocLa/CaiThuocLa/CaiThuocLa/Views/SurveyQuestion/Index.cshtml
@using CaiThuocLa.Code
@using CaiThuocLa.Utility
@model CaiThuocLa.Models.SurveyQuestionModel
@{

    var exportUrl = "/SurveyQuestion/ProcessExport/?" + Request.QueryString;
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading bg-red">
                <h3 class="panel-title"><strong>Thư viện câu hỏi khảo sát</strong></h3>
            </div>
            <div class="panel-body modal-panel">
                <div class="row">
                    <div class="col-md-12">
                        @if (ViewBag.SuccessMessage != null && ViewBag.SuccessMessage != "")
                        {
                            <div class="col-md-12" style="background-color:#5EBD33; padding-top: 5px; padding-bottom: 5px; margin-bottom: 10px; color: #fff;">
                                @ViewBag.SuccessMessage
                            </div>
                        }
                        @if (ViewBag.ErrorMessage != null && ViewBag.ErrorMessage != "")
                        {
                            <div class="col-md-12" style="background-color:#ff0000; padding-top: 5px; padding-bottom: 5px; margin-bottom: 10px; color: #fff;">
                                @ViewBag.ErrorMessage
                            </div>
                        }
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><strong>Tìm kiếm</strong></h3>
                            </div>
                            <div class="panel-body" style="padding-top:10px;padding-bottom:10px;">
                                <div class="row">
                                    <div class="col-md-12">
                                        <form id="form4" role="form" class="icon-validation" method="post">
                                            <div class="form-group">
                                                <label class="control-label">Câu hỏi</label>
                                                <div class="input-icon right">
                                                    <i class="fa"></i>
                                                    @Html.TextBoxFor(model => model.Question, new { @class = "form-control" })
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">Câu trả lời</label>
                                                <div class="input-icon right">
                                                    <i class="fa"></i>
                                                    @Html.TextBoxFor(model => model.AnswersSearch, new { @class = "form-control" })
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">Trạng thái</label>
                                                <div class="input-icon right">
                                                    <i class="fa"></i>
                                                    @{
                                                        Dictionary<string, string> addAllStatus = new Dictionary<string, string>();
                                                        addAllStatus.Add("Tất cả", 0.ToString());
                                                    }
                                                    @Html.EnumDropDownListFor(model => model.Status, addAllStatus, "", new { @class = "form-control" }, new string[] { SurveyQuestionStatus.Đã_xóa.ToString() })
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label">Khảo sát</label>
                                                <div class="input-icon right">
                                                    <i class="fa"></i>
                                                    @Html.DropDownList("SurveyID", (SelectList)ViewBag.SurveyList, new { @class = "form-control" })
                                                </div>
                                            </div>
                                            <div class="form-group text-center">
                                                <button class="btn btn-danger" onclick="javascript:$('#form4').parsley('validate');">Tìm kiếm</button>
                                                <button type="reset" class="btn btn-default">Làm mới</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
                        <a href="/SurveyQuestion/Add" class="btn btn-danger fancybox fancybox.ajax" title="Thêm câu hỏi mới">Thêm mới</a>
                        @Html.Partial("~/Views/Shared/Pager.cshtml", Model.Paging)<br /><br />
                        <table class="table table-striped table-hover dataTable">
                            <thead>
                                <tr role="row">
                                    <th style="text-align:center;">STT</th>
                                    <th style="text-align:center;">Thứ tự gửi</th>
                                    <th style="text-align:center;">Câu hỏi</th>
                                    <th style="text-align:center;">Câu trả lời 1</th>
                                    <th style="text-align:center;">Câu trả lời 2</th>
                                    <th style="text-align:center;">Câu trả lời 3</th>
                                    <th style="text-align:center;">Câu trả lời 4</th>
                                    <th style="text-align:center;">Trạng thái</th>
                                    <th style="text-align:center;">Khảo sát</th>
                                    <th style="text-align:center;">Ngày tạo</th>
                                    <th style="text-align:center;">Hành động</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.DataList != null && Model.DataList.Count() > 0)
                                {
                                    foreach (CaiThuocLa.DTO.SurveyQuestion i in Model.DataList)
                                    {
                                        <tr>
                                            <td style="text-align:center;">@i.ExtentionProperty["RowNum"]</td>
                                            <td style="text-align:center;">@i.QuestionContinueID</td>
                                            <td style="text-align:center;">@i.Question</td>
                                            <td style="text-align:center;">@i.Answers1</td>
                                            <td style="text-align:center;">@i.Answers2</td>
                                            <td style="text-align:center;">@i.Answers3</td>
                                            <td style="text-align:center;">@i.Answers4</td>
                                            <td style="text-align:center;">@CaiThuocLa.Utility.GFunction.EnumDisplay(typeof(CaiThuocLa.Utility.SurveyQuestionStatus).FullName, i.Status)</td>
                                            <td style="text-align:center;">@i.ExtentionProperty["SurveyName"]</td>
                                            <td style="text-align:center;">@String.Format("{0:dd/MM/yyyy HH:mm:ss}", i.CreatedDate)</td>
                                            <td style="text-align:center;">
                                                <a class="fancybox fancybox.ajax" href="/SurveyQuestion/Edit/?id=@i.ID" title="Chỉnh sửa" style="background:#57BEC7;padding:5px;"> <i class="glyphicon glyphicon-pencil"></i></a>&nbsp;
                                                <a href="/SurveyQuestion/Delete/?id=@i.ID" title="Xóa" style="background:#57BEC7;padding:5px;" onclick="return confirm('Bạn có chắc sẽ xóa dữ liệu này?');"><i class="glyphicon glyphicon-remove-sign"></i></a>
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                        @Html.Partial("~/Views/Shared/Pager.cshtml", Model.Paging)
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CaiThuocLa/CaiThuocLa/CaiThuocLa/Views/SurveyQuestion/_SurveyQuestionPatial.cshtml
@using CaiThuocLa.Code
@model List<CaiThuocLa.DTO.SurveyQuestion>

@{
    Layout = "";
    int indexRow = 0;
}

<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
                    <table class="table table-striped table-hover dataTable">
                        <thead>
                            <tr role="row">
                                <th style="text-align:center;">STT</th>
                                <th style="text-align:center;">Thứ tự gửi</th>
                                <th style="text-align:center;">Câu hỏi</th>
                                <th style="text-align:center;">Câu trả lời 1</th>
                                <th style="text-align:center;">Câu trả lời 2</th>
                                <th style="text-align:center;">Câu trả lời 3</th>
                                <th style="text-align:center;">Câu trả lời 4</th>
                                <th style="text-align:center;">Trạng thái</th>
                                <th style="text-align:center;">Ngày tạo</th>
                                <th style="text-align:center;">Hành động</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Count > 0)
                            {
                                foreach (var i in Model)
                                {
                                    <tr>
                                        <td style="text-align:center;">@(++indexRow)</td>
                                        <td style="text-align:center;">@i.QuestionContinueID</td>
                                        <td style="text-align:center;">@i.Question</td>
                                        <td style="text-align:center;">@i.Answers1</td>
                                        <td style="text-align:center;">@i.Answers2</td>
                                        <td style="text-align:center;">@i.Answers3</td>
                                        <td style="text-align:center;">@i.Answers4</td>
                                        <td style="text-align:center;">@i.Status</td>
                                        <td style="text-align:center;">@String.Format("{0:dd/MM/yyyy HH:mm:ss}", i.CreatedDate)</td>
                                        <td style="text-align:center;">
                                            <a class="fancybox fancybox.ajax" href="/SurveyQuestion/EditPatial?id=@i.ID" title="Chỉnh sửa" style="padding:5px;"> <i class="glyphicon glyphicon-pencil"></i></a>&nbsp;
                                            <a href="/SurveyQuestion/DeletePatial?id=@i.ID" title="Xóa" style="padding:5px;" onclick="return confirm('Bạn có chắc sẽ xóa dữ liệu này?');"><i class="glyphicon glyphicon-remove-sign"></i></a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>